# Generated by Django 5.1.4 on 2024-12-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("online_platform", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="provider",
            name="supplier_type",
            field=models.CharField(
                choices=[
                    ("factory", "Завод"),
                    ("retail_network", "Розничная сеть"),
                    ("individual_entrepreneur", "Индивидуальный предприниматель"),
                ],
                max_length=40,
                verbose_name="Тип поставщика",
            ),
        ),
    ]
